Repository JootCamp/Backend, pull requests merged in 2024-06, with the labels that each got.

#24 #23 jpa 설정 추가
  src/main/resources/application.yml
Labels: enhancement

#26 fix(BE) : 401 반환
  src/main/java/com/jootcamp/superboard/common/filter/LoginCheckFilter.java
Labels: bug

#27 fix(BE) : 아이디 중복 확인 ifPresent로 변경
  src/main/java/com/jootcamp/superboard/user/service/UserService.java
  src/main/java/com/jootcamp/superboard/user/service/dto/UpsertUser.java
Labels: bug

#31 Feature/18
  src/main/java/com/jootcamp/superboard/common/filter/LoginCheckFilter.java
Labels: bug

#30 feat(BE) : #22 로그인 체크 기능 구현
  src/main/java/com/jootcamp/superboard/user/controller/UserApiController.java
Labels: enhancement

#32 feat(BE) : 글로버예외추가 BadRequestException
  src/main/java/com/jootcamp/superboard/common/exception/GlobalExceptionHandler.java
Labels: bug

#37 #36 Swagger 설정 및 간단한 사용 예시
  build.gradle
  src/main/java/com/jootcamp/superboard/common/configure/SwaggerConfiguration.java
  src/main/java/com/jootcamp/superboard/common/filter/LoginCheckFilter.java
  src/main/java/com/jootcamp/superboard/user/controller/UserApiController.java
  src/main/resources/application.yml
Labels: enhancement

#38 #29 게시글 생성
  src/main/java/com/jootcamp/superboard/post/controller/PostApiController.java
  src/main/java/com/jootcamp/superboard/post/dto/PostResponse.java
  src/main/java/com/jootcamp/superboard/post/dto/UpsertPostRequest.java
  src/main/java/com/jootcamp/superboard/post/repository/PostRepository.java
  src/main/java/com/jootcamp/superboard/post/repository/entity/PostEntity.java
  src/main/java/com/jootcamp/superboard/post/service/PostService.java
  src/main/java/com/jootcamp/superboard/post/service/dto/Post.java
  src/main/java/com/jootcamp/superboard/post/service/dto/UpsertPost.java
Labels: enhancement, help wanted

#39 #34 게시글 목록 조회, 게시글 조회 기능
  src/main/java/com/jootcamp/superboard/post/controller/PostApiController.java
  src/main/java/com/jootcamp/superboard/post/repository/PostRepository.java
  src/main/java/com/jootcamp/superboard/post/repository/execption/PostNotFoundException.java
  src/main/java/com/jootcamp/superboard/post/service/PostService.java
Labels: enhancement, help wanted

#41 #35 게시글 삭제
  src/main/java/com/jootcamp/superboard/post/controller/PostApiController.java
  src/main/java/com/jootcamp/superboard/post/repository/entity/PostEntity.java
  src/main/java/com/jootcamp/superboard/post/service/PostService.java
Labels: enhancement, help wanted

#42 #33 게시글 수정
  src/main/java/com/jootcamp/superboard/post/controller/PostApiController.java
  src/main/java/com/jootcamp/superboard/post/repository/entity/PostEntity.java
  src/main/java/com/jootcamp/superboard/post/service/PostService.java
Labels: enhancement, help wanted
