Repository JootCamp/Backend, pull requests merged in 2024-09, with the labels that each got.

#88 #50 로그인 성공 시, 쿠키에 JWT 구워주기
  build.gradle
  src/main/java/com/jootcamp/superboard/jwt/JWTUtil.java
  src/main/java/com/jootcamp/superboard/user/controller/UserApiController.java
  src/main/java/com/jootcamp/superboard/user/service/UserService.java
  src/main/resources/application.yml
Labels: enhancement

#93 fix - issue 92 : Post에 BoardId 필드 추가
  src/main/java/com/jootcamp/superboard/post/controller/PostApiController.java
  src/main/java/com/jootcamp/superboard/post/dto/UpsertPostRequest.java
  src/main/java/com/jootcamp/superboard/post/repository/entity/PostEntity.java
  src/main/java/com/jootcamp/superboard/post/service/PostService.java
  src/main/java/com/jootcamp/superboard/post/service/dto/Post.java
  src/main/java/com/jootcamp/superboard/post/service/dto/UpsertPost.java
  src/test/java/com/jootcamp/superboard/post/controller/PostApiControllerTest.java
Labels: bug, enhancement

#94 fix - issue 90 : interceptor 수정
  src/main/java/com/jootcamp/superboard/board/service/BoardService.java
  src/main/java/com/jootcamp/superboard/comment/service/CommentService.java
  src/main/java/com/jootcamp/superboard/common/entity/BaseWithDeletedEntity.java
  src/main/java/com/jootcamp/superboard/common/intercepter/PostCheckInterceptor.java
  src/main/java/com/jootcamp/superboard/post/repository/PostRepository.java
  src/main/java/com/jootcamp/superboard/post/service/PostService.java
Labels: bug, enhancement

#95 fix - issue 91 : WebConfiguration 수정
  src/main/java/com/jootcamp/superboard/board/repository/BoardRepository.java
  src/main/java/com/jootcamp/superboard/board/service/BoardService.java
  src/main/java/com/jootcamp/superboard/common/configure/WebConfiguration.java
  src/main/java/com/jootcamp/superboard/common/interceptor/PostCheckInterceptor.java
  src/main/java/com/jootcamp/superboard/post/repository/PostRepository.java
  src/main/java/com/jootcamp/superboard/post/service/PostService.java
  src/test/java/com/jootcamp/superboard/common/Interceptor/PostCheckInterceptorTest.java
  src/test/java/com/jootcamp/superboard/post/controller/PostApiControllerTest.java
Labels: bug

#97 #fix - issue 96 : options 필터제외
  src/main/java/com/jootcamp/superboard/common/filter/LoginCheckFilter.java
Labels: bug
